"""Blogger permission role added

Revision ID: 272874699cdd
Revises: 945e2d92ef4c
Create Date: 2016-10-19 06:12:40.023903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272874699cdd'
down_revision = '945e2d92ef4c'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('_Blogger__password', sa.Text(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.Text()), nullable=True),
    sa.CheckConstraint('char_length(name) > 0', name=op.f('ck_bloggers_name_len_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bloggers'))
    )
    op.create_index(op.f('ix_bloggers_name'), 'bloggers', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bloggers_name'), table_name='bloggers')
    op.drop_table('bloggers')
    ### end Alembic commands ###
