"""Relation between Blogger and Post

Revision ID: 442e89e0be38
Revises: 400eeabad603
Create Date: 2016-10-20 23:19:34.558450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442e89e0be38'
down_revision = '400eeabad603'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('blogger_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_posts_blogger_id_bloggers'), 'posts', 'bloggers', ['blogger_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posts_blogger_id_bloggers'), 'posts', type_='foreignkey')
    op.drop_column('posts', 'blogger_id')
    ### end Alembic commands ###
