"""Default table deleted

Revision ID: 945e2d92ef4c
Revises: a16e3bc17dc2
Create Date: 2016-10-19 00:05:13.364105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945e2d92ef4c'
down_revision = 'a16e3bc17dc2'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_models')
    )
    ### end Alembic commands ###
