"""Blog model added

Revision ID: b317228532c5
Revises: 272874699cdd
Create Date: 2016-10-20 03:14:45.972130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b317228532c5'
down_revision = '272874699cdd'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('blogger_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blogger_id'], ['bloggers.id'], name=op.f('fk_blogs_blogger_id_bloggers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blogs'))
    )
    op.create_index(op.f('ix_blogs_title'), 'blogs', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_title'), table_name='blogs')
    op.drop_table('blogs')
    ### end Alembic commands ###
