"""Update time added to blog

Revision ID: cea7f1d47d48
Revises: b317228532c5
Create Date: 2016-10-20 19:54:01.992923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea7f1d47d48'
down_revision = 'b317228532c5'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('updated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'updated_on')
    ### end Alembic commands ###
