"""User joining date

Revision ID: 37fb4a75354d
Revises: a8b20fd5c9ec
Create Date: 2016-10-27 01:18:07.308151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37fb4a75354d'
down_revision = 'a8b20fd5c9ec'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'roles',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_column('users', 'joined_on')
    ### end Alembic commands ###
