"""Added Gallery and GalleryImage

Revision ID: 421d2bea30bf
Revises: 8a96ab49746b
Create Date: 2016-10-26 21:47:46.457613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '421d2bea30bf'
down_revision = '8a96ab49746b'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_galleries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_galleries'))
    )
    op.create_index(op.f('ix_galleries_title'), 'galleries', ['title'], unique=False)
    op.create_table('gallery_images',
    sa.Column('basename', sa.Text(), nullable=False),
    sa.Column('_available_sizes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('image_type', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], name=op.f('fk_gallery_images_gallery_id_galleries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery_images')),
    sa.UniqueConstraint('basename', name=op.f('uq_gallery_images_basename'))
    )
    op.alter_column('profile_pictures', '_available_sizes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_pictures', '_available_sizes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_galleries_title'), table_name='galleries')
    op.drop_table('galleries')
    ### end Alembic commands ###
