"""User model added

Revision ID: 819383239033
Revises: 
Create Date: 2016-10-23 23:39:43.598694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819383239033'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('_password_hash', sa.Text(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
