"""Profile picture model added

Revision ID: 8a96ab49746b
Revises: 819383239033
Create Date: 2016-10-26 03:47:59.717945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a96ab49746b'
down_revision = '819383239033'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pictures',
    sa.Column('basename', sa.Text(), nullable=False),
    sa.Column('image_type', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_available_sizes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_pictures_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_pictures')),
    sa.UniqueConstraint('basename', name=op.f('uq_profile_pictures_basename'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_pictures')
    ### end Alembic commands ###
