"""Gallery Image update

Revision ID: a8b20fd5c9ec
Revises: 421d2bea30bf
Create Date: 2016-10-26 21:57:37.385073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b20fd5c9ec'
down_revision = '421d2bea30bf'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_images', sa.Column('uploaded_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery_images', 'uploaded_on')
    ### end Alembic commands ###
