"""DateTime Fix

Revision ID: b53dd755da8b
Revises: 37fb4a75354d
Create Date: 2016-10-27 01:21:06.187035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53dd755da8b'
down_revision = '37fb4a75354d'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
