"""PetType and Pet Modifications

Revision ID: f9557172a7d0
Revises: c14a3f3ef142
Create Date: 2016-11-05 21:30:19.428784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9557172a7d0'
down_revision = 'c14a3f3ef142'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pettype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pettype')),
    sa.UniqueConstraint('name', name=op.f('uq_pettype_name'))
    )
    op.add_column('pet', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_pet_type_id_pettype'), 'pet', 'pettype', ['type_id'], ['id'])
    op.drop_column('pet', 'type')
    ### end Alembic commands ###

    ### Add some Pet types
    from pethouse.models.pet_types import PetType
    from sqlalchemy.orm import Session
    petTypes = [
        PetType(name='Cat'),
        PetType(name='Dog'),
        PetType(name='Fish'),
        PetType(name='Bird'),
        PetType(name='Lizard'),
    ]
    dbsession = Session(bind=op.get_bind())
    dbsession.add_all(petTypes)
    dbsession.commit()



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_pet_type_id_pettype'), 'pet', type_='foreignkey')
    op.drop_column('pet', 'type_id')
    op.drop_table('pettype')
    ### end Alembic commands ###
